name: Build and Package Childcare App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl customtkinter

    - name: Build Executable
      run: |
        pyinstaller --onefile --noconsole --name childcare_app.exe main.py

    - name: Sign Executable
      run: |
        signtool sign /a /tr http://timestamp.digicert.com /td sha256 /fd sha256 /v dist/childcare_app.exe

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: childcare_app
        path: dist/childcare_app.exe